info:
  app:
    name: 配置中心
    description: 配置文件管理
    version: v1.0-dev
server:
  port: 8002
logging:
  level:
    root: info
  path: /root/logs/config-server
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: true
      server:
        native:
          search-locations: classpath:/config
        git:
          uri: https://github.com/k1tCooler/springcloud/tree/master/config/src/main/resources/config/
          username: chenshaokangvip@163.com
          password: 19910207kang
          default-label: null
          search-paths:
          - chrs
          - swt-zuul
        svn:
          uri: svn://172.16.0.8/repo/config-server
          username: himasoft
          password: ohs!mZ8cq^&N*lUd
          default-label: null
          search-paths:
          - chrs
          - swt-zuul
  rabbitmq:
    host: 192.168.4.216
    port: 5672
    username: himasoft
    password: himasoft
management:
  security:
    enabled: false