info:
  app:
    name: 配置中心
    description: 配置文件管理
    version: v1.0
server:
  port: 8100
logging:
  level:
    root: info
  path: /root/logs/config-server
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.0.177:8090/eureka/,http://192.168.4.216:8090/eureka/
spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: true
      server:
        native:
          search-locations: classpath:/config
        svn:
          uri: https://192.168.4.62/svn/CHRS/himasoft-recipes/trunk/spring-cloud-server/config-server/src/main/resources/config/
          username: csk
          password: 123456
          default-label: null
          search-paths:
          - eureka-server
          - chrs
          - swt-zuul
  rabbitmq:
    host: 192.168.4.216
    port: 5672
    username: himasoft
    password: himasoft
management:
  security:
    enabled: false